###
 GET https://localhost/webauthn/webauthn/server.php?fn=getStoredDataHtml

### getStoredDataJson
GET https://localhost/webauthn/webauthn/server.php?fn=getStoredDataJson

### getArgs
GET https://localhost/webauthn/webauthn/server.php?fn=getCreateArgs&mds=1&type_int=1&type_hybrid=1&fmt_none=1&rpId=localhost&userId=64656d6f64656d6f&userName=demo@z.com&userDisplayName=Demo%20Demolin&userVerification=discouraged
